version: '3.7'

networks:
  vps:
    external: false
  internal:
    external: false

volumes:
  gdg_postgres_data:
      driver: local

services:

  gdg-web-app:
    container_name: gdglemans-webapp-container
    build: ./GDGLeMans-WebApp
    ports:
      - '4200:4200'


  gdg-postgres:
    container_name: gdglemans-db-container
    image: postgres:10
    restart: always
    volumes:
        - gdg_postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      POSTGRES_ROOT_PASSWORD: Uf#9HFn%<E]n.^Da
      POSTGRES_DB: db_gdglemans
      POSTGRES_USER: gdglemans
      POSTGRES_PASSWORD: WiMTMxuvT5ZLg07j

  gdg-api:
    container_name: gdglemans-api-container
    build: ./GDGLeMans-API
    depends_on:
      - postgres-adc-dev
    restart: always
    networks:
      - vps
      - internal
    environment:
      ASPNETCORE_AUTHORITY: https://oauth.apsidetop-devel.net/auth/realms/GDG-Le-Mans
      ASPNETCORE_AUDIENCE: gdglemans
      ASPNETCORE_CONNECTION_STRING: Host=gdg-postgres;Port=5432;Username=gdglemans;Password=WiMTMxuvT5ZLg07j;Database=db_gdglemans
    ports:
      - '44324:8090'
